/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyImportCsvImportCsvPost
 */
export interface BodyImportCsvImportCsvPost {
    /**
     * 
     * @type {Blob}
     * @memberof BodyImportCsvImportCsvPost
     */
    file: Blob;
}

export function BodyImportCsvImportCsvPostFromJSON(json: any): BodyImportCsvImportCsvPost {
    return BodyImportCsvImportCsvPostFromJSONTyped(json, false);
}

export function BodyImportCsvImportCsvPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyImportCsvImportCsvPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function BodyImportCsvImportCsvPostToJSON(value?: BodyImportCsvImportCsvPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}


