/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BorrowResponseStatus,
    BorrowResponseStatusFromJSON,
    BorrowResponseStatusFromJSONTyped,
    BorrowResponseStatusToJSON,
} from './';

/**
 * Response model for borrowing a book
 * @export
 * @interface BorrowResponseModel
 */
export interface BorrowResponseModel {
    /**
     * 
     * @type {BorrowResponseStatus}
     * @memberof BorrowResponseModel
     */
    status: BorrowResponseStatus;
    /**
     * 
     * @type {string}
     * @memberof BorrowResponseModel
     */
    returnDate?: string;
}

export function BorrowResponseModelFromJSON(json: any): BorrowResponseModel {
    return BorrowResponseModelFromJSONTyped(json, false);
}

export function BorrowResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BorrowResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': BorrowResponseStatusFromJSON(json['status']),
        'returnDate': !exists(json, 'return_date') ? undefined : json['return_date'],
    };
}

export function BorrowResponseModelToJSON(value?: BorrowResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': BorrowResponseStatusToJSON(value.status),
        'return_date': value.returnDate,
    };
}


