/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * status codes for Borrowing a book
 * @export
 * @enum {string}
 */
export enum BorrowResponseStatus {
    SuccessfullyBorrowed = 'successfully borrowed',
    AlreadyBorrowed = 'already borrowed',
    UserUnknown = 'user unknown',
    MaximumNumberObBooksAlreadyBorrowed = 'maximum number ob books already borrowed'
}

export function BorrowResponseStatusFromJSON(json: any): BorrowResponseStatus {
    return BorrowResponseStatusFromJSONTyped(json, false);
}

export function BorrowResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BorrowResponseStatus {
    return json as BorrowResponseStatus;
}

export function BorrowResponseStatusToJSON(value?: BorrowResponseStatus | null): any {
    return value as any;
}

