/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BorrowingUserRecord
 */
export interface BorrowingUserRecord {
    /**
     * 
     * @type {number}
     * @memberof BorrowingUserRecord
     */
    key: number;
    /**
     * 
     * @type {number}
     * @memberof BorrowingUserRecord
     */
    bookKey: number;
    /**
     * 
     * @type {number}
     * @memberof BorrowingUserRecord
     */
    userKey: number;
    /**
     * 
     * @type {Date}
     * @memberof BorrowingUserRecord
     */
    returnDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BorrowingUserRecord
     */
    expirationDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof BorrowingUserRecord
     */
    startDate: Date;
    /**
     * 
     * @type {string}
     * @memberof BorrowingUserRecord
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BorrowingUserRecord
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof BorrowingUserRecord
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof BorrowingUserRecord
     */
    isbn?: string;
    /**
     * 
     * @type {number}
     * @memberof BorrowingUserRecord
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof BorrowingUserRecord
     */
    shorthand: string;
    /**
     * 
     * @type {string}
     * @memberof BorrowingUserRecord
     */
    firstname: string;
    /**
     * 
     * @type {string}
     * @memberof BorrowingUserRecord
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof BorrowingUserRecord
     */
    classname: string;
}

export function BorrowingUserRecordFromJSON(json: any): BorrowingUserRecord {
    return BorrowingUserRecordFromJSONTyped(json, false);
}

export function BorrowingUserRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BorrowingUserRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'bookKey': json['book_key'],
        'userKey': json['user_key'],
        'returnDate': !exists(json, 'return_date') ? undefined : (new Date(json['return_date'])),
        'expirationDate': (new Date(json['expiration_date'])),
        'startDate': (new Date(json['start_date'])),
        'title': json['title'],
        'author': json['author'],
        'category': json['category'],
        'isbn': !exists(json, 'isbn') ? undefined : json['isbn'],
        'number': json['number'],
        'shorthand': json['shorthand'],
        'firstname': json['firstname'],
        'lastname': json['lastname'],
        'classname': json['classname'],
    };
}

export function BorrowingUserRecordToJSON(value?: BorrowingUserRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'book_key': value.bookKey,
        'user_key': value.userKey,
        'return_date': value.returnDate === undefined ? undefined : (value.returnDate.toISOString().substr(0,10)),
        'expiration_date': (value.expirationDate.toISOString().substr(0,10)),
        'start_date': (value.startDate.toISOString().substr(0,10)),
        'title': value.title,
        'author': value.author,
        'category': value.category,
        'isbn': value.isbn,
        'number': value.number,
        'shorthand': value.shorthand,
        'firstname': value.firstname,
        'lastname': value.lastname,
        'classname': value.classname,
    };
}


