/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * status codes for deleting a book
 * @export
 * @enum {string}
 */
export enum DeleteBookResponseStatus {
    Deleted = 'book deleted',
    StillBorrowed = 'book still borrowed',
    NotDeleted = 'book not deleted'
}

export function DeleteBookResponseStatusFromJSON(json: any): DeleteBookResponseStatus {
    return DeleteBookResponseStatusFromJSONTyped(json, false);
}

export function DeleteBookResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBookResponseStatus {
    return json as DeleteBookResponseStatus;
}

export function DeleteBookResponseStatusToJSON(value?: DeleteBookResponseStatus | null): any {
    return value as any;
}

