/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * status codes for delete a user
 * @export
 * @enum {string}
 */
export enum DeleteUserResponseStatus {
    Deleted = 'user deleted',
    IsStillBorrowingBooks = 'user is still borrowing books',
    NotDeleted = 'user not deleted'
}

export function DeleteUserResponseStatusFromJSON(json: any): DeleteUserResponseStatus {
    return DeleteUserResponseStatusFromJSONTyped(json, false);
}

export function DeleteUserResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserResponseStatus {
    return json as DeleteUserResponseStatus;
}

export function DeleteUserResponseStatusToJSON(value?: DeleteUserResponseStatus | null): any {
    return value as any;
}

