/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeleteUserResponseStatus,
    DeleteUserResponseStatusFromJSON,
    DeleteUserResponseStatusFromJSONTyped,
    DeleteUserResponseStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeleteUserResponseModel
 */
export interface DeleteUserResponseModel {
    /**
     * 
     * @type {DeleteUserResponseStatus}
     * @memberof DeleteUserResponseModel
     */
    status: DeleteUserResponseStatus;
}

export function DeleteUserResponseModelFromJSON(json: any): DeleteUserResponseModel {
    return DeleteUserResponseModelFromJSONTyped(json, false);
}

export function DeleteUserResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': DeleteUserResponseStatusFromJSON(json['status']),
    };
}

export function DeleteUserResponseModelToJSON(value?: DeleteUserResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': DeleteUserResponseStatusToJSON(value.status),
    };
}


