/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExtendingResponseStatus,
    ExtendingResponseStatusFromJSON,
    ExtendingResponseStatusFromJSONTyped,
    ExtendingResponseStatusToJSON,
} from './';

/**
 * Response model for extending a book borrowing period
 * @export
 * @interface ExtendingResponseModel
 */
export interface ExtendingResponseModel {
    /**
     * 
     * @type {ExtendingResponseStatus}
     * @memberof ExtendingResponseModel
     */
    status: ExtendingResponseStatus;
    /**
     * 
     * @type {Date}
     * @memberof ExtendingResponseModel
     */
    returnDate?: Date;
}

export function ExtendingResponseModelFromJSON(json: any): ExtendingResponseModel {
    return ExtendingResponseModelFromJSONTyped(json, false);
}

export function ExtendingResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendingResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': ExtendingResponseStatusFromJSON(json['status']),
        'returnDate': !exists(json, 'return_date') ? undefined : (new Date(json['return_date'])),
    };
}

export function ExtendingResponseModelToJSON(value?: ExtendingResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': ExtendingResponseStatusToJSON(value.status),
        'return_date': value.returnDate === undefined ? undefined : (value.returnDate.toISOString().substr(0,10)),
    };
}


