/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PatchUserResponseStatus,
    PatchUserResponseStatusFromJSON,
    PatchUserResponseStatusFromJSONTyped,
    PatchUserResponseStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface PatchUserResponseModel
 */
export interface PatchUserResponseModel {
    /**
     * 
     * @type {PatchUserResponseStatus}
     * @memberof PatchUserResponseModel
     */
    status: PatchUserResponseStatus;
}

export function PatchUserResponseModelFromJSON(json: any): PatchUserResponseModel {
    return PatchUserResponseModelFromJSONTyped(json, false);
}

export function PatchUserResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchUserResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': PatchUserResponseStatusFromJSON(json['status']),
    };
}

export function PatchUserResponseModelToJSON(value?: PatchUserResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': PatchUserResponseStatusToJSON(value.status),
    };
}


