/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * status codes for updating a book
 * @export
 * @enum {string}
 */
export enum PatchBookResponseStatus {
    Updated = 'book updated',
    NotUpdated = 'book not updated'
}

export function PatchBookResponseStatusFromJSON(json: any): PatchBookResponseStatus {
    return PatchBookResponseStatusFromJSONTyped(json, false);
}

export function PatchBookResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchBookResponseStatus {
    return json as PatchBookResponseStatus;
}

export function PatchBookResponseStatusToJSON(value?: PatchBookResponseStatus | null): any {
    return value as any;
}

