/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * status codes for creating a book
 * @export
 * @enum {string}
 */
export enum PutBookResponseStatus {
    Created = 'book created',
    NotCreated = 'book not created'
}

export function PutBookResponseStatusFromJSON(json: any): PutBookResponseStatus {
    return PutBookResponseStatusFromJSONTyped(json, false);
}

export function PutBookResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutBookResponseStatus {
    return json as PutBookResponseStatus;
}

export function PutBookResponseStatusToJSON(value?: PutBookResponseStatus | null): any {
    return value as any;
}

