/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PutUserResponseStatus,
    PutUserResponseStatusFromJSON,
    PutUserResponseStatusFromJSONTyped,
    PutUserResponseStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface PutUserResponseModel
 */
export interface PutUserResponseModel {
    /**
     * 
     * @type {PutUserResponseStatus}
     * @memberof PutUserResponseModel
     */
    status: PutUserResponseStatus;
}

export function PutUserResponseModelFromJSON(json: any): PutUserResponseModel {
    return PutUserResponseModelFromJSONTyped(json, false);
}

export function PutUserResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutUserResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': PutUserResponseStatusFromJSON(json['status']),
    };
}

export function PutUserResponseModelToJSON(value?: PutUserResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': PutUserResponseStatusToJSON(value.status),
    };
}


