/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * status codes for creating a user
 * @export
 * @enum {string}
 */
export enum PutUserResponseStatus {
    Created = 'user created',
    NotCreated = 'user not created'
}

export function PutUserResponseStatusFromJSON(json: any): PutUserResponseStatus {
    return PutUserResponseStatusFromJSONTyped(json, false);
}

export function PutUserResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutUserResponseStatus {
    return json as PutUserResponseStatus;
}

export function PutUserResponseStatusToJSON(value?: PutUserResponseStatus | null): any {
    return value as any;
}

