/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * status codes for Borrowing a book
 * @export
 * @enum {string}
 */
export enum ReturningResponseStatus {
    SuccessfullyReturned = 'successfully returned',
    BookNotBorrowed = 'book not borrowed',
    UserUnknown = 'user unknown',
    BookUnknown = 'book unknown'
}

export function ReturningResponseStatusFromJSON(json: any): ReturningResponseStatus {
    return ReturningResponseStatusFromJSONTyped(json, false);
}

export function ReturningResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturningResponseStatus {
    return json as ReturningResponseStatus;
}

export function ReturningResponseStatusToJSON(value?: ReturningResponseStatus | null): any {
    return value as any;
}

