/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ReturningResponseStatus,
    ReturningResponseStatusFromJSON,
    ReturningResponseStatusFromJSONTyped,
    ReturningResponseStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface ReturningResponseModel
 */
export interface ReturningResponseModel {
    /**
     * 
     * @type {ReturningResponseStatus}
     * @memberof ReturningResponseModel
     */
    status: ReturningResponseStatus;
}

export function ReturningResponseModelFromJSON(json: any): ReturningResponseModel {
    return ReturningResponseModelFromJSONTyped(json, false);
}

export function ReturningResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturningResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': ReturningResponseStatusFromJSON(json['status']),
    };
}

export function ReturningResponseModelToJSON(value?: ReturningResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': ReturningResponseStatusToJSON(value.status),
    };
}


